# Generated by Django 5.2.9 on 2025-12-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
    ]
